### ISSUE TITLE
implement upload picture of house

### ISSUE THREAD

**Issue by lyuboxin** [new-airbnb/kitchen-towel#32]

**Comment by xingweitian** [comment]
Hi @ericqiangguo , if you have any questions about the upload api, feel free to contact me!

**Comment by ericqiangguo** [comment]
> Hi @ericqiangguo , if you have any questions about the upload api, feel free to contact me!

thanks big xing

**Comment by lyuboxin** [comment]
@ericqiangguo I will help you finish upload. Please give priority to the issue 33 and 45

**Comment by ericqiangguo** [comment]
> @ericqiangguo I will help you finish upload. Please give priority to the issue 33 and 45

Ok thanks boxing
